name: MacOS Test
on:
  push:
    branches:
      - macos
jobs:
  build:
    name: Build for macos
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Pre reqs
        run: |
          brew update
          brew install xz automake binutils coreutils curl gettext libtool openssl pkgconfig
          brew upgrade
      - name: build
        run: ./mac/ci-build.sh
          

