name: check-macos
on:
  push:
    branches: [ "macos" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/lib3270
          releases-only: true
      - name: Install Pre reqs
        run: |
          brew update
          brew install xz meson ninja curl gettext openssl pkgconfig
          brew upgrade
      - name: build
        run: |
          export PKG_CONFIG_PATH="$(brew --prefix curl)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig"
          meson setup --prefix=$(brew --prefix)/Cellar/lib3270/${{ steps.gettag.outputs.tag }} .build       
          meson compile -C .build
  
